### ISSUE TITLE
请问有没有训练 CTPN 模型的带标签的数据

### ISSUE THREAD

**Issue by jijibongsky** [taigege/Bankcard_OCR#2]

**Comment by keDaYao** [comment]
在README.md百度云链接里

**Comment by mayidu** [comment]
您好，百度云连接打不开了，您能重新发一份吗，我的邮箱是mayidu@126.com，感谢啦！

**Comment by mayidu** [comment]
@taigege

**Comment by keDaYao** [comment]
可以在这里尝试搜索一下

训练代码和银行卡的训练集上传到了百度云：链接：https://pan.baidu.com/s/1AbUwbAs_SutehBCBnp881A&amp;shfl=sharepset&nbsp;提取码：5r4j

图片存放在text-detection-ctpn-untagged\data\VOCdevkit2007\VOC2007\JPEGImages下，有2000张左右的训练集。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taigege/Bankcard_OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taigege/Bankcard_OCR] 请问有没有训练 CTPN 模型的带标签的数据 (#2)





 
@taigege

**Comment by mayidu** [comment]
您好，我这边这个链接打开就是这样的，下载不了，您能发送一份给我吗，感谢啦










在 2021-05-24 17:24:57，"Tai" ***@***.***> 写道：

可以在这里尝试搜索一下

训练代码和银行卡的训练集上传到了百度云：链接：https://pan.baidu.com/s/1AbUwbAs_SutehBCBnp881A&amp;shfl=sharepset&nbsp;提取码：5r4j

图片存放在text-detection-ctpn-untagged\data\VOCdevkit2007\VOC2007\JPEGImages下，有2000张左右的训练集。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "taigege/Bankcard_OCR" ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taigege/Bankcard_OCR] 请问有没有训练 CTPN 模型的带标签的数据 (#2)






@taigege

**Comment by keDaYao** [comment]
抱歉，看样子是被删除了，代码时间久远忘记训练集存储在哪里了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taigege/Bankcard_OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taigege/Bankcard_OCR] 请问有没有训练 CTPN 模型的带标签的数据 (#2)





 
 
 
 
 
 
 您好，我这边这个链接打开就是这样的，下载不了，您能发送一份给我吗，感谢啦
 
 
 
 
 
 
 
 
 
 
 在 2021-05-24 17:24:57，"Tai" ***@***.***&gt; 写道：
 
 可以在这里尝试搜索一下
 
 训练代码和银行卡的训练集上传到了百度云：链接：https://pan.baidu.com/s/1AbUwbAs_SutehBCBnp881A&amp;amp;shfl=sharepset&amp;nbsp;提取码：5r4j
 
 图片存放在text-detection-ctpn-untagged\data\VOCdevkit2007\VOC2007\JPEGImages下，有2000张左右的训练集。
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "taigege/Bankcard_OCR" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2021年5月24日(星期一) 下午5:21
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [taigege/Bankcard_OCR] 请问有没有训练 CTPN 模型的带标签的数据 (#2)
 
 
 
 
 
 
 @taigege
